version: '3.8'
services:
  db:
    image: mysql-projeto-anotacoes
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: anotacoes
    ports:
      - "3306:3306"
    networks:
      - devs2blu-network
  backend-projeto-anotacoes:
    image: backend-projeto-anotacoes
    restart: always
    build: ./projeto-anotacoes
    working_dir: /projeto-anotacoes
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./projeto-anotacoes:/projeto-anotacoes
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - devs2blu-network
networks:
    devs2blu-network:
        driver: bridge
